import { anthropic } from "@ai-sdk/anthropic";
import { generateObject, tool } from "ai";
import { z } from "zod";
import { MODELS } from "@/lib/ai/models";
import { PANEL_SIMULATOR_SYSTEM } from "@/lib/ai/prompts/panel-simulator";
import { InstrumentSchema, type Instrument } from "@/lib/schemas/instrument";
import {
  RespondentSchema,
  type PanelResult,
  type Respondent,
} from "@/lib/schemas/panel";
import { PersonaSchema, type Persona } from "@/lib/schemas/persona";

function personaSummary(persona: Persona): string {
  const d = persona.demographics;
  return [
    `Name: ${persona.name}`,
    `Demographics: ${d.ageRange} ${d.gender}, ${d.location}, ${d.occupation}`,
    `Traits: ${persona.characteristics.join("; ")}`,
    `Pain points: ${persona.painPoints.join("; ")}`,
    `Goals: ${persona.goals.join("; ")}`,
  ].join("\n");
}

function instrumentSummary(instrument: Instrument): string {
  const items = instrument.items
    .map((it, i) => `${i}. [${it.responseType}] ${it.question}`)
    .join("\n");
  return [
    `Title: ${instrument.title}`,
    `Description: ${instrument.description}`,
    `Items (use itemIndex to reference):`,
    items,
  ].join("\n");
}

async function runOneRespondent(
  index: number,
  total: number,
  persona: Persona,
  instrument: Instrument,
): Promise<Respondent> {
  const id = `R${String(index + 1).padStart(2, "0")}`;
  const prompt = `You are respondent ${id} (one of ${total}).

PERSONA ARCHETYPE
${personaSummary(persona)}

INSTRUMENT
${instrumentSummary(instrument)}

Respond as ${id}. Set id="${id}". Provide a brief identifying name and answers for every item (one entry per itemIndex 0..${instrument.items.length - 1}).`;

  const { object } = await generateObject({
    model: anthropic(MODELS.panelRespondent),
    system: PANEL_SIMULATOR_SYSTEM,
    prompt,
    schema: RespondentSchema,
  });
  return { ...object, id };
}

export const panelSimulator = tool({
  description:
    "Simulate a panel of synthetic respondents answering an instrument. Each respondent is generated by a separate Sonnet call in parallel. Use after persona and instrument exist; pass them inline.",
  inputSchema: z.object({
    persona: PersonaSchema,
    instrument: InstrumentSchema,
    panelSize: z
      .number()
      .optional()
      .describe(
        "Number of synthetic respondents to simulate (1-10). Omit for the default of 4.",
      ),
  }),
  execute: async ({ persona, instrument, panelSize }): Promise<PanelResult> => {
    const size = Math.min(Math.max(panelSize ?? 4, 1), 10);
    const respondents = await Promise.all(
      Array.from({ length: size }, (_, i) =>
        runOneRespondent(i, size, persona, instrument),
      ),
    );
    return { panelSize: size, respondents };
  },
});
